/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  esaenz
 * Created: 01/11/2018
 */

ALTER TABLE APP.GROUP_MEMBERS
ADD FOREIGN KEY (USERNAME) 
REFERENCES APP.USERS(USERNAME)



ALTER TABLE APP.AUTHORITIES  ALTER COLUMN USERNAME NOT NULL;
ALTER TABLE APP.AUTHORITIES  ALTER COLUMN AUTHORITY NOT NULL;
ALTER TABLE APP.AUTHORITIES ADD PRIMARY KEY(USERNAME, AUTHORITY)


ALTER TABLE APP.GROUP_AUTHORITIES  ALTER COLUMN GROUP_ID NOT NULL;
ALTER TABLE APP.GROUP_AUTHORITIES  ALTER COLUMN AUTHORITY NOT NULL;
ALTER TABLE APP.GROUP_AUTHORITIES ADD PRIMARY KEY(GROUP_ID, AUTHORITY)

